# Task 1. Order and Sales Analysis

#Total Number Of Orders
SELECT 
count(order_id) as number_of_orders
FROM 
customer_orders;
-- Total number of orders 15000

#Order Status Summary 
SELECT 
order_status,
count(*) as number_of_orders
FROM 
customer_orders
GROUP BY 
order_status;
-- pending orders are 5069
-- delivered orders are 5057
-- shipped orders are 4874

#Total Revenue(sales) Generated
SELECT
sum(order_amount) as total_revenue
FROM 
customer_orders;
-- Total revenue generated is  3808899

#Revenue Generated by Order Status
SELECT 
order_status,
sum(order_amount) as revenue
FROM 
customer_orders
GROUP BY 
order_status
ORDER BY 
revenue DESC;
-- Delivered revenue 1284616
-- pending revenue 1278400
-- shipped revenue 1245883

#Orders Per Month
SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(order_id) AS orders_in_month
FROM customer_orders
GROUP BY month
ORDER BY month;
-- The Avearge orders per month is nearly 200

#Revenue Per Month
SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    SUM(order_amount) AS revenue_in_month
FROM customer_orders
GROUP BY month
ORDER BY month;
-- The average revenue generated per month is nearly 60000


